name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Check
        run: vp check

      - name: Build
        run: vp build

      - name: Publish
        run: pnpm publish --access public --provenance --config.publish-branch=master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
